include infra Schema during infra update
OpsLevel/opslevel-go pull request #387
Opened 2024-03-26 20:36 UTC by davidbloss

## Issues

The terraform provider is unable to update an infrastructure resource's `schema` field. This fixes that.

## Changelog

- [X] List your changes here
- [X] Make a `changie` entry

## Tophatting

`task test` - all tests pass

2024-03-26 21:00 UTC, taimoorgit requested changes

2024-03-26 21:00 UTC, taimoorgit commented on infra_test.go
> +		`{"all": true, "identifier": { {{ template "id1" }}}, "input": { "ownerId": "{{ template "id1_string" }}", "schema": {"type": ""}, "data": "{\"endpoint\":\"https://google.com\",\"engine\":\"BigQuer
I noticed the create test uses a schema with a type, can that be added here?

https://github.com/OpsLevel/opslevel-go/blob/f4f74660988fc296978001baf6ea0b0c8c242e7a/infra_test.go#L25-L27

2024-03-27 15:30 UTC, taimoorgit approved these changes
>The terraform provider is unable to update an infrastructure resource's schema field. This fixes that.

Change and test LGTM but do we even want to do this in the TF upgrade? Would this be out of scope?

2024-03-27 15:41 UTC, davidbloss commented
> > The terraform provider is unable to update an infrastructure resource's schema field. This fixes that.
> 
> Change and test LGTM but do we even want to do this in the TF upgrade? Would this be out of scope?

Why this is in scope:
- Looking at the [TF upgrade ticket](https://github.com/OpsLevel/team-platform/issues/308) acceptance criteria
   - "Data input to and returned from each resource should match the structure, types, etc..."
- Adding the missing `Schema` field here within the `UpdateInfrastructure()` func fixes a bug. When customers change their [opslevel_infrastructure](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/infrastructure#schema) schema, specifically the `opslevel_infrastructure.schema` field it works on create but fails on update.
- The underlying schema hasn't changed (no input change) and this doesn't change the expected output from the terraform provider. It just fixes it.

2024-03-27 15:41 UTC, merged