Eo/3243 ctm issue
OpsLevel/opslevel-go pull request #74
Opened 2022-07-27 22:00 UTC by eochoa260

2022-07-27 22:06 UTC, rocktavious requested changes
Let me know if this all doesn't make sense - we can walk through it on a call.  Its a tricky thing so I want to make sure you fully understand the root of the problem.

2022-07-27 22:06 UTC, rocktavious commented on check.go
> +	Notes       *string      `graphql:"notes"`
This is not needed as this is on the "response" side.  The passing of null is only needed on the "request variables" side IE input

2022-07-27 22:06 UTC, rocktavious commented on check.go
> +	Notes    *string       `json:"notes"`
this doesn't actually need to be a pointer we just need to remove the `omitempty` to the "input" on the update mutation passes and empty string - the `omitempty` is droping the field "notes" from the variables on the mutation.

2022-07-27 22:06 UTC, rocktavious commented on check.go
> +	Notes    *string       `json:"notes"`
no need for a pointer here - and we should keep the `omitemtpy` since this is on the "create" side.  The "update" is what the problem is.

2022-07-28 18:58 UTC, eochoa260 commented
@rocktavious ok, I tested with `""`, `null`, and text and the update worked in all cases.  I tried creating a test case on the opslevel-go side but couldn't get it to work.  I couldn't set Notes field to nil since it said that it wasn't a valid string value.

2022-07-28 21:52 UTC, rocktavious approved these changes
👍

2022-07-29 01:46 UTC, merged